### ISSUE TITLE
Spelling error in the website

### ISSUE THREAD

**Issue by Q7v** [aoijs/website#140]
### What happened?

- https://aoi.js.org/functions/database-related/getmessagevar/#_top 
- [Replace guildID with messageID]
![image](https://github.com/aoijs/website/assets/96356762/dbf65555-61d8-4757-bbbc-9e1f8647bad2)

-------------------------------------------------------------------------------------------------------------------
- https://aoi.js.org/functions/util-related/charcount/#_top 
- [Replace a with a]
![image](https://github.com/aoijs/website/assets/96356762/399ce62b-21aa-4681-a906-a92a54a2b0e4)
-------------------------------------------------------------------------------------------------------------------
There are some that have been repaired so I have nothing left but this

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Fixed in latest commit.
