### ISSUE TITLE
Searches don't work in docs.

### ISSUE THREAD

**Issue by AlissomDeveloper** [aoijs/website#152]
I was trying to search for a function, but it said it didn't find any results. This occurs when I enter any letter, it says it found no results.

#### Images:
![Screenshot_20240310-135040](https://github.com/aoijs/website/assets/140280010/3da6b2e9-2206-47de-baeb-3379402e57d9)
![Screenshot_20240310-135035](https://github.com/aoijs/website/assets/140280010/ddebb1e1-72a7-43e6-8b4b-47b37f7fadf1)
![Screenshot_20240310-135024](https://github.com/aoijs/website/assets/140280010/5f5630fa-7084-406e-9b43-4fb7514ee94a)

**Comment by Faf4a** [comment]
Fixed, sorry for the inconvenience.
