### ISSUE TITLE
Use the natively built-in search engine plugin 

### ISSUE THREAD

**Issue by Leref** [aoijs/website#153]
### What happened?

[This](https://starlight.astro.build/guides/site-search/) over a component.

it’s self explanatory.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
Can't do this unless the component has support for custom props

**Comment by Faf4a** [comment]
done
