### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by VR2211** [aoijs/website#181]
My discord account was recently hacked where do u send a messgae in order to get unbaned and join the server again.

Thank You in Advanced.

**Comment by Faf4a** [comment]
@VR2211 would you mind telling me your discord ID?

**Comment by VR2211** [comment]
@Faf4a I do not know if it is safe to post my discord id publicly is there any other way, I can send it to you.

Thank you

**Comment by Faf4a** [comment]
add me on discord, @catpurrrchino
